# Generated by Django 5.2.1 on 2025-08-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headName', models.CharField(max_length=50)),
                ('members', models.IntegerField()),
            ],
        ),
    ]
